# Generated by Django 2.0.2 on 2018-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180308_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_Favorite',
            field=models.BooleanField(default=False),
        ),
    ]
